### ISSUE TITLE
"Remix on Glitch" initial app not running due to chokidar dependency

### ISSUE THREAD

**Issue by mn113** [stimulusjs/stimulus#315]
I've clicked the link "Remix on Glitch" from the Handbook, here https://stimulusjs.org/handbook/hello-stimulus

Once the Glitch app is created, it fails to run, this error is in the logs:

I'll try again tomorrow in case it's a temporary thing. [Edit: tried after 12 hours, still an issue]

```
Listening on port 3000
/rbd/pnpm-volume/9817a593-3b6f-400b-85ca-433923e8b4f5/node_modules/.registry.npmjs.org/watchpack/1.7.2/node_modules/watchpack/lib/chokidar.js:17
throw new Error(
^
Error: No version of chokidar is available. Tried chokidar@2 and chokidar@3.
You could try to manually install any chokidar version.
chokidar@3: Error: Cannot find module 'normalize-path'
chokidar@2: Error: Cannot find module 'watchpack-chokidar2'
    at Object.<anonymous> (/rbd/pnpm-volume/9817a593-3b6f-400b-85ca-433923e8b4f5/node_modules/.registry.npmjs.org/watchpack/1.7.2/node_modules/watchpack/lib/chokidar.js:17:7)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/rbd/pnpm-volume/9817a593-3b6f-400b-85ca-433923e8b4f5/node_modules/.registry.npmjs.org/watchpack/1.7.2/node_modules/watchpack/lib/DirectoryWatcher.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by javan** [comment]
Should be working now. See https://github.com/stimulusjs/stimulus-starter/issues/8.
